packages:
  - "../primebrick-fe-v3"
  - "../primebrick-be-v3"
  - "../primebrick-us-v3"
  - "../primebrick-us-v3/emailsender"
  - "../primebrick-us-v3/ai"
  - "../primebrick-dal-v3"
  - "../primebrick-v3-sdk"
  - "../primebrick-v3-docs"